### ISSUE TITLE
Create User Research Templates

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#101]
As a User Researcher

I WANT a set of customised user research templates

SO THAT I do not have to create new documents each time

 

Background: To make ongoing user research activities easier and standardised across the team, we need to create a set of templates that the team can use on an ongoing basis.

The value of doing this will be:

reducing time spent searching for templates,
we can be in line with CJH standards and
ways of working become consistent
 

Acceptance Criteria
- [x] The Essex County Council and other repositories have been reviewed
- [x] The templates cover the research methods mentioned in the UR Approach Document
- [x] Templates are customised using Criminal Justice colours and style
- [x] The templates are available on SharePoint
- [x] The templates have been reviewed by the UR Lead
- [ ] The Team have been notified and are aware of templates available

**Comment by noniUR** [comment]
**Created the following templates**

**Planning** 
	• Research Plan
	• Research participants List
	
**Interviews** 
	• Interview Discussion Guide
	• Participant consent form: link and instructions 
	• Participant information sheet template

**User Testing**
	• User Testing Discussion Guide template 

**Emails** 
	• Confirming a research session 
	• Reminding a participant of a session 
	• Thanking a participant 

**Note taking**
Debriefing / Synthesis Template (should be migrated to Miro decision)

**Comment by noniUR** [comment]
Added a few more templates
- Call for participation email template
- User interviews recruitment email
- Participant screener survey
- User research findings report

**Comment by lfriedman1321** [comment]
@legaleagleryan to check and sign off - let the team know when drafts are approved

**Comment by legaleagleryan** [comment]
> @legaleagleryan to check and sign off - let the team know when drafts are approved

Approved
