### ISSUE TITLE
Volunteer Ticket - Content Blocks Issue

### ISSUE THREAD

**Issue by jarvisryan** [criminaljusticehub/sprint-board#133]
#### Overview
A team member is encountering significant hurdles with the Drupal CMS while attempting to set up a Service Landing Page for the 'About' page on the new site. Despite a general comfort with CMSs and having watched the instructional videos, the user is facing issues that prevent the page from functioning as intended.

#### Issues Encountered

1. **Content Visibility Issue**:
   - After adding a Service Landing Page for the 'About' page, the content does not appear when the page is viewed. This issue is critical as it prevents any information from being displayed to site visitors.

2. **Missing Content Blocks**:
   - Unlike expected, there are no 'content blocks' available to add to the 'About' page. Content blocks were discussed in a previous meeting to ensure that all pages have access to blocks for a consistent design across the site. However, the option to add or select page components (e.g., 'Page Component - add or select') is missing from the Service Landing Page created by the user.
   - On an existing page ('Accessibility'), a button allows adding/selecting page components, but this functionality is absent from the newly created Service Landing Page. Furthermore, even the 'Accessibility' page lacks a list of components to add when attempting to add/create a component.

#### Request for Assistance

The team member is willing to collaborate on identifying and creating the necessary components for the site's content strategy but is seeking guidance due to limited Drupal expertise.

#### Action Items

1. **Investigate and Resolve Content Visibility Issue**: Determine why the content is not showing on the newly created 'About' page and implement a fix.
2. **Address Missing Content Blocks Functionality**:
   - Diagnose why the option to add content blocks is not available on the Service Landing Page and rectify this issue.
   - Ensure that a list of components is accessible when attempting to add/create a component to a page, resolving the discrepancy observed on the 'Accessibility' page.

**Comment by legaleagleryan** [comment]
Hey @fdunnington think I have figured out the issue. 

The service landing page will only allow you to link to other pages which need to be created first.

The service page content type should allow you to add page blocks which I think is what you wanted. 

I know @carolinechristie1 is looking to do a session at this weeks @criminaljusticehub/content-design-team meeting which I am hoping to attend to help if anything doesn't work as planned 😊
