### ISSUE TITLE
Review existing Google analytics data

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#17]
##What 
There is some existing Google Analytics data for the current website. We should analyse this to see current usage, most popular websites, broken pages, people searching for things that aren't there, etc. to create a potential list of new content ideas.

## Acceptance Criteria

- [ ] Summary of Google Analytics data complete
- [ ] Recommendations on the back of the data have been made with next steps/actions detailed

## Readiness

***Please check this meets the Definition of Ready before it is added to the backlog***
- [ ] The story or task has a **concise and understandable description**
- [ ] **Acceptance criteria** are specific, well-defined to clarify when task is considered complete
- [ ] Any **dependencies**, whether they are on other tasks/teams/external factors, are clearly outlined
- [ ] Initial **estimation** of effort or complexity is provided to help with prioritisation and planning
- [ ] The task has been assigned a **priority** level indicating importance in overall backlog
- [ ] Any relevant **attachments** - documents, mock-ups, additional info - that aid understanding are attached
- [ ] Clear how task will be **tested** to ensure it meets specified criteria
- [ ] All relevant **stakeholders** have provided input or approval for task

***Please check this meets the Definition of Done. before it is moved to the 'done' column***

- [ ] All code related to task is implemented and reviewed
- [ ] Unit tests written and passed to ensure functionality works as intended
- [ ] Integration Tests conducted to verify implemented code works well with other components
- [ ] Necessary documentation is complete, including code comments and user documentation
- [ ] Code has undergone a thorough review by peers or designated reviewer
- [ ] Task meets all acceptance criteria
- [ ] Comprehensive testing including regression testing has been performed to fix any bugs
- [ ] Performance aspects e.g., speed & resource usage, considered and meet defined standards
- [ ] Code ready for deployment in live environment
- [ ] Product manager or relevant stakeholders reviewed and approved completed task

**Comment by legaleagleryan** [comment]
Please let me know if you require access or need assistance in accessing the Google Analytics Data. You will need to create a Google Account first using your @criminaljusticehub email address.

**Comment by legaleagleryan** [comment]
@criminaljusticehub/user-research-team @criminaljusticehub/content-design-team

**Comment by legaleagleryan** [comment]
Please see [Google Analytics Summary](https://criminaljusticesystem.sharepoint.com/:w:/s/criminal-justice-hub-service-design-team/ETv0fWFXpjtEmB7UXfTiFEkBxCSaJM-BL_eQyW7_3f3fJg?e=DgbIzd) by @felicity-spencer and [Google Analytics Review](https://criminaljusticesystem.sharepoint.com/:p:/s/criminal-justice-hub-service-design-team/EXplRMMjITtLhq6yeNbp4sUBY5JRgwn36V0ggTcP3YtbFA?e=FxmNo0) by @raphmalek
