### ISSUE TITLE
REMOVED - EPIC: Create a design system

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#2]
**What?**

To create a place for the Service Design Team to find styles, components and patterns for designing Criminal Justice Hub services.

**Why?**

- **Consistency:** With a design system, we can ensure that all our digital services and products have a consistent look and feel. This consistency reinforces user trust and makes it easier for users to navigate different services because they become familiar with the recurring design patterns.

- **Accessibility:** The design system will be built with accessibility in mind, ensuring that digital services are usable by as many people as possible, including those with disabilities. This is not just good practice; it's a legal requirement.

- **Efficiency and Speed:** By using a design system, teams across the criminal justice system can design and build faster since they are reusing components and patterns that have already been tested and iterated upon.

- **Collaboration:** The design system will encourage collaboration across the criminal justice system. Different departments can contribute to and benefit from a shared system, avoiding duplication of work and fostering a community of practice.

- **Quality:** With a shared design system, the criminal justice system can maintain high-quality standards across all its digital services. It ensures that components and patterns are tested for usability and are built to meet the needs of a wide range of users.

- **Cost-Effectiveness:** It is more cost-effective to design and develop digital services using standardised guidelines and components. It reduces the need for external design resources and minimises the costs associated with creating bespoke designs for every new service.

- **User-Centric Approach:** The design system puts user needs at the forefront. By focusing on the elements that work best for the end-user, we can provide more effective and user-friendly services.

- **Documentation and Guidance:** It offers detailed documentation and guidance for designers and developers, making it easier for new projects to get off the ground with clear best practices in mind.

- **Scalability:** As more services are added, the design system can scale to meet increasing demands without sacrificing performance or usability.

**Designs in the wild**

[Croydon Design System](https://design-system.croydon.gov.uk)
[GOV.UK Design System](https://design-system.service.gov.uk)
[Home Office Design System](https://design.homeoffice.gov.uk)
[Department for Education Design System](https://design.education.gov.uk/design-system)
[Ministry of Defence Design System](https://design-system.service.mod.gov.uk)
[Department for Work and Pensions Design System](https://design-system.dwp.gov.uk/index)
[NHS Design System](https://service-manual.nhs.uk/design-system)
[NHS Digital Design System](https://design-system.digital.nhs.uk)

**Comment by legaleagleryan** [comment]
@criminaljusticehub/content-design-team @criminaljusticehub/user-research-team @criminaljusticehub/product-management-team @criminaljusticehub/devops-team

**Comment by lfriedman1321** [comment]
Removing this - discussed that we would use existing GDS design system
