### ISSUE TITLE
Design Content and Survey for old website to seek feedback from current users

### ISSUE THREAD

**Issue by jarvisryan** [criminaljusticehub/sprint-board#28]
**What?**

Please can the @criminaljusticehub/user-research-team review the current banner at the top for the current website and design a survey for our current users to seek feedback as we build the new service. 

**Why?**

This will assist with trying to find out what current user pain points are, what they would like to see on the new site and hopefully assist us with segmenting content for our different types of users - for example, offenders, family members, professionals etc. 

**When?**

To be agreed with Head of User Research and @criminaljusticehub/product-management-team 

**Current Banner**

![image](https://github.com/criminaljusticehub/sprint-board/assets/84692125/76ed88b1-ee02-4ecb-9d67-4a54800ed6f9)

## Acceptance Criteria

- [x] Survey has been designed
- [ ] Agreed process for monitoring and capturing responses

## Readiness

***Please check this meets the Definition of Ready before it is added to the backlog***
- [ ] The story or task has a **concise and understandable description**
- [ ] **Acceptance criteria** are specific, well-defined to clarify when task is considered complete
- [ ] Any **dependencies**, whether they are on other tasks/teams/external factors, are clearly outlined
- [ ] Initial **estimation** of effort or complexity is provided to help with prioritisation and planning
- [ ] The task has been assigned a **priority** level indicating importance in overall backlog
- [ ] Any relevant **attachments** - documents, mock-ups, additional info - that aid understanding are attached
- [ ] Clear how task will be **tested** to ensure it meets specified criteria
- [ ] All relevant **stakeholders** have provided input or approval for task

***Please check this meets the Definition of Done. before it is moved to the 'done' column***

- [ ] All code related to task is implemented and reviewed
- [ ] Unit tests written and passed to ensure functionality works as intended
- [ ] Integration Tests conducted to verify implemented code works well with other components
- [ ] Necessary documentation is complete, including code comments and user documentation
- [ ] Code has undergone a thorough review by peers or designated reviewer
- [ ] Task meets all acceptance criteria
- [ ] Comprehensive testing including regression testing has been performed to fix any bugs
- [ ] Performance aspects e.g., speed & resource usage, considered and meet defined standards
- [ ] Code ready for deployment in live environment
- [ ] Product manager or relevant stakeholders reviewed and approved completed task

**Comment by felicity-spencer** [comment]
Not sure how many volunteers we'll need on this one, but happy to be assigned to this too. Thank you!

**Comment by lfriedman1321** [comment]
Thanks @felicity-spencer  - have assigned it to you for now. I think Gavin was planning to pull together a call with the user research team but haven't seen anything come through yet

**Comment by felicity-spencer** [comment]
@lfriedman1321 no problem, thank you!

**Comment by lfriedman1321** [comment]
@GavinSkull can you please review the survey that Felicity has started?
Can someone take responsibility for creating it and linking to the banner?

**Comment by legaleagleryan** [comment]
You can find the survey created by @felicity-spencer [here](https://criminaljusticesystem.sharepoint.com/:w:/s/criminal-justice-hub-service-design-team/EcsHEBQte9FHhRuroX5GFsIBEvDMxeVeP5lcETu-2kfAdg?e=B818iT).

@GavinSkull  - Could you inform us about the user researchers involved in the survey and its response analysis? We need this information to establish a dedicated private channel on Teams for this purpose. Additionally, we aim to restrict access to the responses to ensure privacy, especially if any personal information is shared.

**Comment by legaleagleryan** [comment]
Assigned to @felicity-spencer and @raphmalek.
@GavinSkull to Review

[Separate Private Team has been setup for access to the form responses](https://teams.microsoft.com/l/channel/19%3AkWZLZHTvG2GONaHC8C8JbC9wdl_LcT7kCT0r_TTMafg1%40thread.tacv2/?groupId=b50bec8a-8b07-4dc6-8561-26a260abf439&tenantId=0c8c5000-87e8-425d-9ff9-b5749101f83d). 

There is an email address assigned to the Team which is website-feedback-survey@criminaljusticehub.org.uk which can be used for seeking responses or other feedback if needed [(Accessible Here)](https://outlook.office.com/mail/group/criminaljusticehub.org.uk/website-feedback-survey/email/inbox)

**Comment by lfriedman1321** [comment]
@criminaljusticehub/user-research-team  and @raphmalek  to review length of survey and recruitment of individuals on the back of this - @legaleagleryan any issues with us asking people if they're willing to do a follow-up interview on back of survey?

**Comment by legaleagleryan** [comment]
Survey is now live on the current website and responses accessible to @lfriedman1321 @carolinechristie1 @GavinSkull @felicity-spencer @japhetbonney @raphmalek at https://teams.microsoft.com/l/entity/81fef3a6-72aa-4648-a763-de824aeafb7d/_djb2_msteams_prefix_3979111792?context=%7B%22channelId%22%3A%2219%3AkWZLZHTvG2GONaHC8C8JbC9wdl_LcT7kCT0r_TTMafg1%40thread.tacv2%22%7D&tenantId=0c8c5000-87e8-425d-9ff9-b5749101f83d
