### ISSUE TITLE
Review existing service standards as examples

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#53]

**Comment by legaleagleryan** [comment]
The GOV.UK [Service Standard](https://www.gov.uk/service-manual/service-standard) provides the principles of building a good service. This manual explains what teams can do to build great services that will meet the standard.

The NHS [Service Standard](https://service-manual.nhs.uk/standards-and-technology/service-standard) is designed to help teams meet the GOV.UK service standard in the context of health and care.

**Comment by lfriedman1321** [comment]
@legaleagleryan @carolinechristie1  to discuss if we need our own service standards, or take the approach of the MoJ in terms of assessing ourselves against the Gov UK ones.

**Comment by lfriedman1321** [comment]
As agreed - will draft a checklist/self-assessment against the existing GOV.UK service standard
