### ISSUE TITLE
Community Rules

### ISSUE THREAD

**Issue by jarvisryan** [criminaljusticehub/sprint-board#80]
Current

![Image](https://github.com/criminaljusticehub/sprint-board/assets/84692125/9efc2582-cac1-45b0-9ca2-825e1730d153)

https://www.criminaljusticehub.org.uk/about/policies/community-rules/

**Comment by legaleagleryan** [comment]
Community Rules
1. Be kind and courteous.
We’re all in this together to create a welcoming environment. Let’s treat everyone with respect. Healthy debates are natural, but kindness is required.

2. No hate speech or bullying.
Make sure that everyone feels safe. Bullying of any kind isn’t allowed, and degrading comments about things such as race, religion, culture, sexual orientation, gender or identity will not be tolerated.

3. No promotions or spam.
Give more to this community than you take. Self-promotion, spam and irrelevant links aren’t allowed.

4. Respect everyone’s privacy.
Being part of this community requires mutual trust. Authentic, expressive discussions make communities great, but may also be sensitive and private. What’s shared in the community should stay in the community.

**Comment by carolinechristie1** [comment]
V1 draft copy - https://docs.google.com/document/d/1sANs0uHaf2OGfp7HC3md9VRsU537RGQlVhRQKfF4UaI/edit

**Comment by legaleagleryan** [comment]
This page no longer meets a user need. The new website will not have a comment facility on content items. 

The team decided that this content item is no longer needed.
